<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Football.Simulation.Api\Football.Simulation.Api.csproj" />
    <ProjectReference Include="..\Football.Simulation.Persistence.Sqlite\Football.Simulation.Persistence.Sqlite.csproj" />
  </ItemGroup>
</Project>
